// <auto-generated />
using backend.DataSource;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace backend.Migrations
{
    [DbContext(typeof(PostgreSqlDataContext))]
    [Migration("20180119094435_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("backend.Model.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Country");

                    b.Property<Guid?>("CustomerId");

                    b.Property<string>("Emails");

                    b.Property<string>("PhoneNumbers");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Socials");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("AddressId");

                    b.HasIndex("City");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PostalCode");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("backend.Model.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("BirthDay");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Memo")
                        .HasMaxLength(250);

                    b.Property<short>("Number")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Salutation")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("CustomerId");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("backend.Model.Address", b =>
                {
                    b.HasOne("backend.Model.Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId");
                });
#pragma warning restore 612, 618
        }
    }
}
